name: py37-torch22
channels:
  - pytorch
  - nvidia
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - _py-xgboost-mutex=2.0=gpu_0
  - access=1.1.9=pyhd8ed1ab_1
  - adjusttext=1.3.0=pyhd8ed1ab_0
  - affine=2.4.0=pyhd8ed1ab_0
  - amply=0.1.6=pyhd8ed1ab_0
  - anyio=3.5.0=py37h06a4308_0
  - argon2-cffi=21.3.0=pyhd3eb1b0_0
  - argon2-cffi-bindings=21.2.0=py37h7f8727e_0
  - arpack=3.7.0=hdefa2d7_2
  - attrs=22.1.0=py37h06a4308_0
  - aws-requests-auth=0.4.3=pyhd8ed1ab_0
  - backcall=0.2.0=pyhd3eb1b0_0
  - beautifulsoup4=4.11.1=py37h06a4308_0
  - blas=1.0=mkl
  - bleach=4.1.0=pyhd3eb1b0_0
  - blosc=1.21.1=h83bc5f7_3
  - boost-cpp=1.74.0=h6cacc03_7
  - boto3=1.33.13=pyhd8ed1ab_0
  - botocore=1.33.13=pyhd8ed1ab_0
  - bottleneck=1.3.5=py37hda87dfa_0
  - branca=0.7.2=pyhd8ed1ab_0
  - brotli=1.1.0=hb9d3cd8_2
  - brotli-bin=1.1.0=hb9d3cd8_2
  - brotlipy=0.7.0=py37h27cfd23_1003
  - bzip2=1.0.8=h5eee18b_6
  - c-ares=1.34.4=hb9d3cd8_0
  - ca-certificates=2025.7.14=hbd8a1cb_0
  - cairo=1.16.0=ha12eb4b_1010
  - certifi=2024.8.30=pyhd8ed1ab_0
  - cffi=1.15.1=py37h43b0acd_1
  - cfitsio=4.1.0=hd9d235c_0
  - charset-normalizer=2.0.4=pyhd3eb1b0_0
  - click-plugins=1.1.1=py_0
  - cligj=0.7.2=pyhd8ed1ab_1
  - coin-or-cbc=2.10.12=h8b142ea_1
  - coin-or-cgl=0.60.6=he2f9439_0
  - coin-or-clp=1.17.6=h256e9bb_3
  - coin-or-osi=0.108.7=h3b589db_0
  - coin-or-utils=2.11.6=h573740c_0
  - coincbc=2.10.12=1_metapackage
  - colorama=0.4.6=pyhd8ed1ab_0
  - comm=0.2.2=pyhd8ed1ab_0
  - cryptography=38.0.2=py37h5994e8b_1
  - cuda=11.6.1=0
  - cuda-cccl=11.6.55=hf6102b2_0
  - cuda-command-line-tools=11.6.2=0
  - cuda-compiler=11.6.2=0
  - cuda-cudart=11.6.55=he381448_0
  - cuda-cudart-dev=11.6.55=h42ad0f4_0
  - cuda-cuobjdump=11.6.124=h2eeebcb_0
  - cuda-cupti=11.6.124=h86345e5_0
  - cuda-cuxxfilt=11.6.124=hecbf4f6_0
  - cuda-driver-dev=11.6.55=0
  - cuda-gdb=12.4.127=0
  - cuda-libraries=11.6.1=0
  - cuda-libraries-dev=11.6.1=0
  - cuda-memcheck=11.8.86=0
  - cuda-nsight=12.4.127=0
  - cuda-nsight-compute=12.4.1=0
  - cuda-nvcc=11.6.124=hbba6d2d_0
  - cuda-nvdisasm=12.4.127=0
  - cuda-nvml-dev=11.6.55=haa9ef22_0
  - cuda-nvprof=12.4.127=0
  - cuda-nvprune=11.6.124=he22ec0a_0
  - cuda-nvrtc=11.6.124=h020bade_0
  - cuda-nvrtc-dev=11.6.124=h249d397_0
  - cuda-nvtx=11.6.124=h0630a44_0
  - cuda-nvvp=12.4.127=0
  - cuda-runtime=11.6.1=0
  - cuda-samples=11.6.101=h8efea70_0
  - cuda-sanitizer-api=12.4.127=0
  - cuda-toolkit=11.6.1=0
  - cuda-tools=11.6.1=0
  - cuda-version=11.8=hcce14f8_3
  - cuda-visual-tools=11.6.1=0
  - cudatoolkit=11.8.0=h6a678d5_0
  - curl=7.86.0=h2283fc2_1
  - cycler=0.11.0=pyhd8ed1ab_0
  - debugpy=1.5.1=py37h295c915_0
  - decorator=5.1.1=pyhd3eb1b0_0
  - defusedxml=0.7.1=pyhd3eb1b0_0
  - deprecation=2.1.0=pyh9f0ad1d_0
  - docutils=0.19=py37h89c1867_0
  - entrypoints=0.4=py37h06a4308_0
  - esda=2.3.6=pyhd8ed1ab_0
  - expat=2.6.4=h5888daf_0
  - ffmpeg=4.3=hf484d3e_0
  - flit-core=3.6.0=pyhd3eb1b0_0
  - folium=0.16.0=pyhd8ed1ab_0
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=h77eed37_3
  - fontconfig=2.14.2=h14ed4e7_0
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=0
  - fonttools=4.38.0=py37h540881e_0
  - freetype=2.12.1=h4a9f257_0
  - freexl=1.0.6=h166bdaf_1
  - gdal=3.4.3=py37hed81ac4_0
  - gds-tools=1.9.1.3=0
  - geopandas=0.10.2=pyhd8ed1ab_1
  - geopandas-base=0.10.2=pyha770c72_1
  - geos=3.10.2=h9c3ff4c_0
  - geotiff=1.7.1=h509b78c_1
  - gettext=0.21.1=h27087fc_0
  - giflib=5.2.2=h5eee18b_0
  - glpk=4.65=h9202a9a_1004
  - gmp=6.2.1=h295c915_3
  - gmpy2=2.1.2=py37h025e8b9_0
  - gnutls=3.6.15=he1e5248_0
  - hdf4=4.2.15=h10796ff_3
  - hdf5=1.12.1=nompi_h4df4325_104
  - icu=69.1=h9c3ff4c_0
  - idna=3.4=py37h06a4308_0
  - importlib_metadata=4.11.3=hd3eb1b0_0
  - importlib_resources=5.2.0=pyhd3eb1b0_1
  - inequality=1.0.0=py_0
  - intel-openmp=2021.4.0=h06a4308_3561
  - ipykernel=6.15.2=py37h06a4308_0
  - ipython=7.31.1=py37h06a4308_1
  - ipython_genutils=0.2.0=pyhd3eb1b0_1
  - ipywidgets=8.1.5=pyhd8ed1ab_0
  - jbig=2.1=h7f98852_2003
  - jedi=0.18.1=py37h06a4308_1
  - jinja2=3.1.2=py37h06a4308_0
  - jmespath=1.0.1=pyhd8ed1ab_0
  - joblib=1.3.2=pyhd8ed1ab_0
  - jpeg=9e=h5eee18b_3
  - json-c=0.16=hc379101_0
  - jsonlines=1.2.0=pyh9f0ad1d_2
  - jsonschema=4.17.3=py37h06a4308_0
  - jupyter_client=7.4.9=py37h06a4308_0
  - jupyter_core=4.11.2=py37h06a4308_0
  - jupyter_server=1.23.4=py37h06a4308_0
  - jupyterlab_pygments=0.1.2=py_0
  - jupyterlab_widgets=3.0.13=pyhd8ed1ab_0
  - kealib=1.4.14=h87e4c3c_3
  - keyutils=1.6.1=h166bdaf_0
  - krb5=1.19.3=h08a2579_0
  - lame=3.100=h7b6447c_0
  - lcms2=2.12=h3be6417_0
  - ld_impl_linux-64=2.40=h12ee557_0
  - leidenalg=0.8.9=py37hd23a5d3_0
  - lerc=3.0=h295c915_0
  - libblas=3.9.0=12_linux64_mkl
  - libbrotlicommon=1.1.0=hb9d3cd8_2
  - libbrotlidec=1.1.0=hb9d3cd8_2
  - libbrotlienc=1.1.0=hb9d3cd8_2
  - libcblas=3.9.0=12_linux64_mkl
  - libcublas=11.9.2.110=h5e84587_0
  - libcublas-dev=11.9.2.110=h5c901ab_0
  - libcufft=10.7.1.112=hf425ae0_0
  - libcufft-dev=10.7.1.112=ha5ce4c0_0
  - libcufile=1.9.1.3=0
  - libcufile-dev=1.9.1.3=0
  - libcurand=10.3.5.147=0
  - libcurand-dev=10.3.5.147=0
  - libcurl=7.86.0=h2283fc2_1
  - libcusolver=11.3.4.124=h33c3c4e_0
  - libcusparse=11.7.2.124=h7538f96_0
  - libcusparse-dev=11.7.2.124=hbbe9722_0
  - libdap4=3.20.6=hd7c4107_2
  - libdeflate=1.10=h7f98852_0
  - libedit=3.1.20230828=h5eee18b_0
  - libev=4.33=hd590300_2
  - libexpat=2.6.4=h5888daf_0
  - libffi=3.4.2=h7f98852_5
  - libgcc=14.2.0=h77fa898_1
  - libgcc-ng=14.2.0=h69a702a_1
  - libgdal=3.4.3=h3886835_0
  - libgfortran=14.2.0=h69a702a_1
  - libgfortran-ng=14.2.0=h69a702a_1
  - libgfortran5=14.2.0=hd5240d6_1
  - libglib=2.70.2=h174f98d_4
  - libgomp=14.2.0=h77fa898_1
  - libiconv=1.16=h5eee18b_3
  - libidn2=2.3.4=h5eee18b_0
  - libkml=1.3.0=h238a007_1014
  - liblapack=3.9.0=12_linux64_mkl
  - liblapacke=3.9.0=12_linux64_mkl
  - libllvm11=11.1.0=hf817b99_3
  - libnetcdf=4.8.1=nompi_h329d8a1_102
  - libnghttp2=1.47.0=he49606f_0
  - libnpp=11.6.3.124=hd2722f0_0
  - libnpp-dev=11.6.3.124=h3c42840_0
  - libnsl=2.0.1=hd590300_0
  - libnvjpeg=11.6.2.124=hd473ad6_0
  - libnvjpeg-dev=11.6.2.124=hb5906b9_0
  - libpng=1.6.39=h5eee18b_0
  - libpq=14.2=h676c864_0
  - libpysal=4.7.0=pyhd8ed1ab_0
  - librttopo=1.1.0=hf69c175_9
  - libsodium=1.0.18=h7b6447c_0
  - libspatialindex=1.9.3=h9c3ff4c_4
  - libspatialite=5.0.1=ha867d66_15
  - libsqlite=3.45.2=h2797004_0
  - libssh2=1.11.0=h0841786_0
  - libstdcxx=14.2.0=hc0a3c3a_1
  - libstdcxx-ng=14.2.0=h4852527_1
  - libtasn1=4.19.0=h5eee18b_0
  - libtiff=4.3.0=h542a066_3
  - libunistring=0.9.10=h27cfd23_0
  - libuuid=2.38.1=h0b41bf4_0
  - libwebp=1.2.4=h11a3e52_1
  - libwebp-base=1.2.4=h5eee18b_1
  - libxcb=1.13=h7f98852_1004
  - libxgboost=1.6.2=cuda112h075c576_1
  - libxml2=2.9.12=h885dcf4_1
  - libxslt=1.1.33=h0ef7038_3
  - libzip=1.10.1=h2629f0a_3
  - libzlib=1.2.13=h4ab18f5_6
  - lxml=4.8.0=py37h540881e_2
  - lz4-c=1.9.4=h6a678d5_1
  - markupsafe=2.1.1=py37h7f8727e_0
  - matplotlib-base=3.5.2=py37hc347a89_0
  - matplotlib-inline=0.1.6=py37h06a4308_0
  - metis=5.1.0=hd0bcaf9_1007
  - mgwr=2.2.1=pyhd8ed1ab_0
  - mistune=0.8.4=py37h14c3975_1001
  - mkl=2021.4.0=h06a4308_640
  - mkl-service=2.4.0=py37h7f8727e_0
  - mkl_fft=1.3.1=py37hd3c417c_0
  - mkl_random=1.2.2=py37h51133e4_0
  - mpc=1.3.1=hfe3b2da_0
  - mpfr=4.2.1=h9458935_0
  - mpmath=1.3.0=pyhd8ed1ab_0
  - munch=2.5.0=py_0
  - munkres=1.1.4=pyh9f0ad1d_0
  - nb_conda_kernels=2.3.1=py37h06a4308_0
  - nbclassic=0.5.2=py37h06a4308_0
  - nbclient=0.5.13=py37h06a4308_0
  - nbconvert=6.5.4=py37h06a4308_0
  - nbformat=5.7.0=py37h06a4308_0
  - nccl=2.25.1.1=h03a54cd_0
  - ncurses=6.4=h6a678d5_0
  - nest-asyncio=1.5.6=py37h06a4308_0
  - nettle=3.7.3=hbbd107a_1
  - notebook=6.5.2=py37h06a4308_0
  - notebook-shim=0.2.2=py37h06a4308_0
  - nsight-compute=2024.1.1.4=0
  - nspr=4.36=h5888daf_0
  - nss=3.77=h2350873_0
  - numexpr=2.7.3=py37he8f5f7f_1
  - numpy=1.21.5=py37h6c91a56_3
  - numpy-base=1.21.5=py37ha15fc14_3
  - openh264=2.1.1=h4ff587b_0
  - openjpeg=2.5.0=h7d73246_0
  - openssl=3.1.8=h7b32b05_0
  - packaging=22.0=py37h06a4308_0
  - pandocfilters=1.5.0=pyhd3eb1b0_0
  - parso=0.8.3=pyhd3eb1b0_0
  - pcre=8.45=h9c3ff4c_0
  - pexpect=4.8.0=pyhd3eb1b0_3
  - pickleshare=0.7.5=pyhd3eb1b0_1003
  - pillow=9.4.0=py37h6a678d5_0
  - pip=22.3.1=py37h06a4308_0
  - pixman=0.44.2=h29eaf8c_0
  - pkgutil-resolve-name=1.3.10=py37h06a4308_0
  - poppler=22.04.0=h1434ded_0
  - poppler-data=0.4.12=hd8ed1ab_0
  - postgresql=14.2=hce44dc1_0
  - proj=9.0.0=h93bde94_1
  - prometheus_client=0.14.1=py37h06a4308_0
  - prompt-toolkit=3.0.36=py37h06a4308_0
  - psutil=5.9.0=py37h5eee18b_0
  - pthread-stubs=0.4=hb9d3cd8_1002
  - ptyprocess=0.7.0=pyhd3eb1b0_2
  - py-xgboost=1.6.2=cuda112py37h01c6645_1
  - pycparser=2.21=pyhd3eb1b0_0
  - pygments=2.11.2=pyhd3eb1b0_0
  - pyopenssl=23.0.0=py37h06a4308_0
  - pyparsing=3.1.4=pyhd8ed1ab_0
  - pyrsistent=0.18.0=py37heee7806_0
  - pysocks=1.7.1=py37_1
  - python=3.7.12=hf930737_100_cpython
  - python-dateutil=2.8.2=pyhd3eb1b0_0
  - python-fastjsonschema=2.16.2=py37h06a4308_0
  - python_abi=3.7=4_cp37m
  - pytorch=1.13.1=py3.7_cuda11.6_cudnn8.3.2_0
  - pytorch-cuda=11.6=h867d48c_1
  - pytorch-mutex=1.0=cuda
  - pytz=2024.2=pyhd8ed1ab_0
  - pyzmq=23.2.0=py37h6a678d5_0
  - quantecon=0.7.2=pyhd8ed1ab_0
  - quilt3=5.4.0=pyhd8ed1ab_0
  - rasterio=1.2.10=py37h2f36e39_5
  - rasterstats=0.20.0=pyhd8ed1ab_0
  - readline=8.2=h5eee18b_0
  - requests=2.28.1=py37h06a4308_0
  - requests-futures=1.0.0=pyh9f0ad1d_2
  - rtree=1.0.1=py37h0b55af0_0
  - rvlib=0.0.6=py37hb1e94ed_1
  - s3transfer=0.8.2=pyhd8ed1ab_0
  - scikit-learn=1.0.2=py37hf9e9bfc_0
  - scipy=1.7.3=py37hf2a6cf1_0
  - seaborn=0.12.2=hd8ed1ab_0
  - seaborn-base=0.12.2=pyhd8ed1ab_0
  - segregation=2.3.1=pyhd8ed1ab_1
  - send2trash=1.8.0=pyhd3eb1b0_1
  - setuptools=65.6.3=py37h06a4308_0
  - setuptools-scm=6.4.2=pyhd8ed1ab_0
  - six=1.16.0=pyhd3eb1b0_1
  - snappy=1.1.9=hbd366e4_1
  - sniffio=1.2.0=py37h06a4308_1
  - snuggs=1.4.7=pyhd8ed1ab_1
  - soupsieve=2.3.2.post1=py37h06a4308_0
  - spint=1.0.7=pyhd8ed1ab_1
  - splot=1.1.7=pyhd8ed1ab_0
  - spvcm=0.3.0=pyhd8ed1ab_1
  - sqlite=3.45.2=h2c6b66d_0
  - suitesparse=5.10.1=h5a4f163_3
  - sympy=1.10.1=py37h89c1867_1
  - tbb=2022.0.0=hdb19cb5_0
  - tenacity=8.2.3=pyhd8ed1ab_0
  - terminado=0.17.1=py37h06a4308_0
  - texttable=1.7.0=pyhd8ed1ab_0
  - threadpoolctl=3.1.0=pyh8a188c0_0
  - tiledb=2.8.3=h3f4058f_1
  - tinycss2=1.2.1=py37h06a4308_0
  - tk=8.6.14=h39e8969_0
  - tobler=0.9.0=pyhd8ed1ab_0
  - torchaudio=0.13.1=py37_cu116
  - torchvision=0.14.1=py37_cu116
  - tornado=6.2=py37h5eee18b_0
  - tqdm=4.67.1=pyhd8ed1ab_0
  - traitlets=5.7.1=py37h06a4308_0
  - typing-extensions=4.4.0=py37h06a4308_0
  - typing_extensions=4.7.1=pyha770c72_0
  - tzcode=2024b=hb9d3cd8_0
  - tzdata=2024b=hc8b5060_0
  - unicodedata2=14.0.0=py37h540881e_1
  - urllib3=1.26.14=py37h06a4308_0
  - wcwidth=0.2.5=pyhd3eb1b0_0
  - webencodings=0.5.1=py37_1
  - websocket-client=0.58.0=py37h06a4308_4
  - wheel=0.38.4=py37h06a4308_0
  - widgetsnbextension=4.0.13=pyhd8ed1ab_0
  - xerces-c=3.2.3=h8ce2273_4
  - xgboost=1.6.2=cuda112py37h3ad14e0_1
  - xorg-kbproto=1.0.7=hb9d3cd8_1003
  - xorg-libice=1.1.2=hb9d3cd8_0
  - xorg-libsm=1.2.5=he73a12e_0
  - xorg-libx11=1.8.4=h0b41bf4_0
  - xorg-libxau=1.0.12=hb9d3cd8_0
  - xorg-libxdmcp=1.1.5=hb9d3cd8_0
  - xorg-libxext=1.3.4=h0b41bf4_2
  - xorg-libxrender=0.9.10=h7f98852_1003
  - xorg-renderproto=0.11.1=hb9d3cd8_1003
  - xorg-xextproto=7.3.0=hb9d3cd8_1004
  - xorg-xproto=7.0.31=hb9d3cd8_1008
  - xyzservices=2023.5.0=pyhd8ed1ab_0
  - xz=5.4.6=h5eee18b_1
  - yaml=0.2.5=h7f98852_2
  - zeromq=4.3.5=h6a678d5_0
  - zipp=3.15.0=pyhd8ed1ab_0
  - zlib=1.2.13=h4ab18f5_6
  - zstd=1.5.6=hc292b87_0
  - pip:
      - anndata==0.8.0
      - astropy==2.0.3
      - boltons==24.1.0
      - click==8.1.7
      - contextlib2==21.6.0
      - coverage==7.2.7
      - cvxopt==1.3.2
      - debtcollector==2.5.0
      - dit==1.2.3
      - dnspython==2.3.0
      - exceptiongroup==1.2.2
      - fiona==1.9.6
      - future==1.0.0
      - giddy==2.3.4
      - h5py==3.8.0
      - hyperopt==0.1.2
      - igraph==0.10.8
      - importlib-metadata==6.7.0
      - iniconfig==2.0.0
      - kiwisolver==1.4.5
      - lattices==0.3.5
      - llvmlite==0.39.1
      - louvain==0.8.2
      - lpips==0.1.4
      - mapclassify==2.6.0
      - matplotlib==3.5.3
      - momepy==0.5.4
      - natsort==8.4.0
      - networkx==2.6.3
      - numba==0.56.4
      - opencv-contrib-python==4.10.0.84
      - pandas==1.3.5
      - patsy==1.0.1
      - platformdirs==4.0.0
      - pltable==1.1.0
      - pluggy==1.2.0
      - pointpats==2.2.0
      - pot==0.9.5
      - prettytable==3.7.0
      - progressbar==2.5
      - pulp==2.9.0
      - pycddlib==2.1.7
      - pygeos==0.14
      - pymongo==4.7.3
      - pynndescent==0.5.13
      - pypoman==1.1.0
      - pyproj==3.2.1
      - pysal==2.5.0
      - pytest==7.4.4
      - pytest-cov==4.1.0
      - python-igraph==0.11.8
      - pyyaml==6.0.1
      - scanpy==1.9.3
      - scikit-misc==0.1.4
      - scvi==0.6.8
      - session-info==1.0.0
      - shapely==2.0.6
      - simplejson==3.19.3
      - spaghetti==1.6.5
      - spglm==1.0.8
      - spopt==0.4.1
      - spreg==1.3.2
      - statsmodels==0.13.5
      - stdlib-list==0.10.0
      - tangram-sc==1.0.3
      - tomli==2.0.1
      - umap==0.1.1
      - umap-learn==0.5.7
      - wrapt==1.16.0
      - xlrd==2.0.1
prefix: /data/hgh/anaconda3/envs/py37-torch22
